import type { MarketRegionCoverage, MarketTask } from "./marketMonitoringModel";

export const marketRegionCoverage: readonly MarketRegionCoverage[] = [
  {
    label: "齐齐哈尔指定范围",
    detail: "梅里斯区、8县、讷河市",
    townshipCount: "待核定",
    villageCount: "待核定",
    sourceNote: "等待2025—2026年属地官方完整底册",
    sourceState: "待核定",
  },
  {
    label: "黑河市全域",
    detail: "覆盖全市县区与乡镇样本网络",
    townshipCount: "65个乡镇 · 乡镇与街道合计76个",
    villageCount: "567个行政村",
    sourceNote: "2025—2026年黑河市官方公开口径",
    sourceState: "已核定",
  },
  {
    label: "呼伦贝尔指定范围",
    detail: "扎兰屯、阿荣旗、莫旗、鄂伦春旗",
    townshipCount: "扎兰屯12个 · 鄂伦春10个",
    villageCount: "扎兰屯130个 · 莫旗220个",
    sourceNote: "其余字段等待2025—2026年属地官方底册",
    sourceState: "部分核定",
  },
];

export const marketTasks: readonly MarketTask[] = [
  {
    id: "MK-2026-31018",
    target: "subject",
    targetName: "讷河恒泰米业",
    role: "rice-mill",
    grain: "paddy",
    region: "讷河市",
    owner: "王洋",
    deadline: "今天 17:00",
    status: "填写中",
    completedFields: 18,
    applicableFields: 24,
  },
  {
    id: "MK-2026-31021",
    target: "subject",
    targetName: "龙江北方粮贸有限公司",
    role: "trader",
    grain: "corn",
    region: "龙江县",
    owner: "赵晨",
    deadline: "今天 17:00",
    status: "待审核",
    completedFields: 18,
    applicableFields: 18,
  },
  {
    id: "MK-2026-31023",
    target: "subject",
    targetName: "北安大豆蛋白有限公司",
    role: "soy-protein",
    grain: "soybean",
    region: "黑河市北安市",
    owner: "孙悦",
    deadline: "明天 12:00",
    status: "已退回",
    completedFields: 13,
    applicableFields: 16,
  },
  {
    id: "MK-2026-31025",
    target: "subject",
    targetName: "梅里斯惠农农资服务部",
    role: "agri-dealer",
    grain: "agri-input",
    region: "梅里斯达斡尔族区",
    owner: "周楠",
    deadline: "明天 12:00",
    status: "填写中",
    completedFields: 7,
    applicableFields: 9,
  },
  {
    id: "MK-2026-31027",
    target: "logistics",
    targetName: "齐齐哈尔铁路货运站",
    role: "rail-node",
    grain: "corn",
    region: "齐齐哈尔市",
    owner: "王洋",
    deadline: "今天 17:00",
    status: "填写中",
    completedFields: 9,
    applicableFields: 12,
  },
  {
    id: "MK-2026-31031",
    target: "logistics",
    targetName: "扎兰屯公路物流监测点",
    role: "road-node",
    grain: "corn",
    region: "扎兰屯市",
    owner: "陈佳",
    deadline: "明天 12:00",
    status: "填写中",
    completedFields: 6,
    applicableFields: 9,
  },
];

export const marketSubjectRows = [
  {
    name: "讷河恒泰米业",
    roles: "米厂 · 贸易 · 仓储",
    grain: "稻谷",
    varieties: "龙粳31 · 绥粳18",
    qualityScope: "水分、杂质、不完善粒、出糙率、出米率",
    region: "讷河市",
    owner: "王洋",
    status: "正常监测",
  },
  {
    name: "龙江北方粮贸有限公司",
    roles: "贸易商",
    grain: "玉米 · 大豆",
    varieties: "德美亚3号 · 黑农84",
    qualityScope: "按玉米 / 大豆模板采集",
    region: "龙江县",
    owner: "赵晨",
    status: "正常监测",
  },
  {
    name: "北安大豆蛋白有限公司",
    roles: "大豆蛋白加工",
    grain: "大豆",
    varieties: "黑农84 · 东生22",
    qualityScope: "蛋白、水分、杂质、不完善粒",
    region: "黑河市北安市",
    owner: "孙悦",
    status: "资料待补",
  },
  {
    name: "莫旗国家粮食储备库",
    roles: "承储 · 储备库",
    grain: "玉米 · 大豆",
    varieties: "样本填报后形成清单",
    qualityScope: "按品类与库存批次采集",
    region: "莫力达瓦旗",
    owner: "刘宇",
    status: "正常监测",
  },
  {
    name: "梅里斯惠农农资服务部",
    roles: "农资经销商",
    grain: "种子 · 农药 · 化肥",
    varieties: "种子品种与农资商品名称由样本填报",
    qualityScope: "规格、有效成分、养分含量与计量单位",
    region: "梅里斯达斡尔族区",
    owner: "周楠",
    status: "正常监测",
  },
] as const;

export const marketLogisticsRows = [
  {
    name: "齐齐哈尔铁路货运站",
    type: "铁路站点",
    coverage: "齐齐哈尔及周边县区",
    monitoring: "包粮 / 散粮、到达 / 发运、即期报价 / 成交价",
    owner: "王洋",
    status: "正常监测",
  },
  {
    name: "扎兰屯公路物流监测点",
    type: "公路物流节点",
    coverage: "扎兰屯南部通道",
    monitoring: "包粮 / 散粮、流入 / 流出、运单 / 过磅",
    owner: "陈佳",
    status: "正常监测",
  },
] as const;
